In [16]:
import numpy as np
import pandas as pd
import statsmodels.api as sm

import matplotlib.pyplot as plt
plt.style.use('ggplot')

In [86]:
path_to_data_file = './Map-Q12021_data.xlsx'
df1 = pd.read_excel(path_to_data_file)
df1.rename(columns={"Full County Number": "FIPS"}, inplace = True)
df1.set_index('FIPS', inplace = True)
df1

,Price-RangeQ12021,Geography,growth Q12021,growth,Price-RangeQ12021.1,Price-RangeQ42020,Latitude (generated),Longitude (generated),ABS-diff price Q1 2021,ABS-diff price Q4 2020,abs-diff-price,Diff price Q3 2020,Diff price Q4 2020,Q1 2021,Q4 2020 Price
FIPS,,,,,,,,,,,,,,,
0,0,US,0,0,0,0,0.0000,0.0000,0.000,0.000,0.000,0.000,0.000000,0.0,0.0
1001,"$150,000-$350,000","Autauga County, Alabama",rose,rose,"$150,000-$350,000","$150,000-$350,000",32.5081,-86.6513,0.063,0.052,0.037,0.037,0.052215,163383.0,161743.0
1003,"$150,000-$350,000","Baldwin County, Alabama",rose,rose,"$150,000-$350,000","$150,000-$350,000",30.7725,-87.7842,0.139,0.119,0.036,0.036,0.118684,238582.0,234357.0
1005,"Less than $150,000","Barbour County, Alabama",dropped,dropped,"Less than $150,000","Less than $150,000",31.8832,-85.3931,0.034,0.051,0.036,0.036,-0.051247,96994.0,95277.0
1007,"Less than $150,000","Bibb County, Alabama",dropped,dropped,"Less than $150,000","Less than $150,000",33.0388,-87.0967,0.023,0.033,0.047,0.047,-0.032950,99436.0,98445.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56037,"$150,000-$350,000","Sweetwater County, Wyoming",rose,dropped,"$150,000-$350,000","$150,000-$350,000",41.6405,-108.9887,0.006,0.011,0.025,0.025,-0.010652,217245.0,213576.0
56039,"$750,000-$1,000,000","Teton County, Wyoming",rose,rose,"$750,000-$1,000,000","$750,000-$1,000,000",43.9385,-110.5501,0.055,0.037,0.025,0.025,0.037229,915682.0,900218.0
56041,"$150,000-$350,000","Uinta County, Wyoming",dropped,dropped,"$150,000-$350,000","$150,000-$350,000",41.3156,-110.5477,0.007,0.024,0.025,0.025,-0.023638,184911.0,181789.0
56043,"$150,000-$350,000","Washakie County, Wyoming",rose,rose,"$150,000-$350,000","$150,000-$350,000",43.8356,-107.6602,0.027,0.009,0.025,0.025,0.009179,175190.0,172232.0
56045,"$150,000-$350,000","Weston County, Wyoming",dropped,dropped,"$150,000-$350,000","$150,000-$350,000",43.8403,-104.5684,0.014,0.031,0.025,0.025,-0.030673,175719.0,172751.0

In [77]:
df1['Q1 2021'].describe()

count    3.120000e+03
mean     1.711000e+05
std      1.102318e+05
min      0.000000e+00
25%      1.048768e+05
50%      1.394700e+05
75%      1.979262e+05
max      1.185951e+06
Name: Q1 2021, dtype: float64

In [33]:
path_to_data_file2 = './RuralAtlasData23.xlsx'
df2 = pd.read_excel(path_to_data_file2, 'People')
df2.set_index('FIPS', inplace = True)
df2

,State,County,PopChangeRate1819,PopChangeRate1019,TotalPopEst2019,NetMigrationRate1019,NaturalChangeRate1019,Net_International_Migration_Rate_2010_2019,PopChangeRate0010,NetMigrationRate0010,...,TotalPopEst2014,TotalPopEst2011,Net_International_Migration_2010_2019,NaturalChange1019,TotalPopEst2015,TotalPopEst2016,TotalPopEst2017,NetMigration1019,TotalPopEst2018,TotalPopEstBase2010
FIPS,,,,,,,,,,,,,,,,,,,,,
0,US,United States,0.475,6.116,328239523,2.485,3.631,2.485,9.709135,NaN,...,318301008,311556874,7685444.0,11232413.0,320635163,322941311,324985539,7685444.0,326687501,308758105
1000,AL,Alabama,0.317,2.461,4903185,1.059,1.402,0.809,7.479841,3.304431,...,4841799,4799069,38731.0,67083.0,4852347,4863525,4874486,50665.0,4887681,4780125
1001,AL,Autauga,0.605,2.001,55869,0.686,1.315,-0.029,24.959355,11.867063,...,54893,55227,-16.0,720.0,54864,55243,55390,376.0,55533,54597
1003,AL,Baldwin,2.469,21.911,223234,21.001,0.910,0.714,29.804508,26.166320,...,199183,186558,1307.0,1667.0,202939,207601,212521,38455.0,217855,182265
1005,AL,Barbour,-0.748,-9.664,24686,-8.797,-0.867,0.161,-5.444590,-4.800965,...,26755,27341,44.0,-237.0,26283,25806,25157,-2404.0,24872,27455
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72145,PR,Vega Baja,NaN,-16.015,50023,NaN,NaN,NaN,-3.660644,NaN,...,55942,58688,NaN,NaN,54805,53677,52318,NaN,50136,59662
72147,PR,Vieques,NaN,-9.963,8386,NaN,NaN,NaN,2.141445,NaN,...,9081,9247,NaN,NaN,8965,8833,8666,NaN,8362,9301
72149,PR,Villalba,NaN,-17.803,21372,NaN,NaN,NaN,-6.591911,NaN,...,24256,25542,NaN,NaN,23662,23091,22452,NaN,21436,26073
72151,PR,Yabucoa,NaN,-14.765,32282,NaN,NaN,NaN,-3.325180,NaN,...,35732,37361,NaN,NaN,35076,34363,33519,NaN,32254,37941
72153,PR,Yauco,NaN,-19.731,33575,NaN,NaN,NaN,-9.358831,NaN,...,38535,41036,NaN,NaN,37585,36654,35474,NaN,33853,41947

In [11]:
df3 = pd.read_excel(path_to_data_file2, 'Jobs')
df4 = pd.read_excel(path_to_data_file2, 'County Classifications')
df5 = pd.read_excel(path_to_data_file2, 'Veterans')
df6 = pd.read_excel(path_to_data_file2, 'Income')

In [32]:
df3

,FIPS,State,County,UnempRate2020,PctEmpChange1920,UnempRate2019,PctEmpChange1819,UnempRate2018,UnempRate2017,UnempRate2016,...,NumUnemployed2015,NumUnemployed2014,NumEmployed2014,NumCivLaborforce2014,NumUnemployed2013,NumCivLaborforce2013,NumUnemployed2007,NumEmployed2007,NumCivLaborforce2007,NumCivLaborforce2017
0,0,US,United States,8.1,-6.0,3.7,1.3,3.9,4.4,4.9,...,8285731.0,9617207.0,146318952.0,155936159.0,11457241.0,155362278.0,7034917.0,145156133.0,152191050.0,160214378.0
1,1000,AL,Alabama,5.9,-3.2,3.0,2.3,3.9,4.6,5.9,...,131852.0,146010.0,2018705.0,2164715.0,159274.0,2172102.0,88418.0,2092030.0,2180448.0,2172455.0
2,1001,AL,Autauga,4.9,-3.9,2.7,1.7,3.6,4.0,5.1,...,1335.0,1489.0,24150.0,25639.0,1628.0,25783.0,824.0,23610.0,24434.0,25898.0
3,1003,AL,Baldwin,5.6,-3.6,2.8,3.7,3.6,4.2,5.4,...,4874.0,5281.0,81265.0,86546.0,5740.0,85206.0,2616.0,80213.0,82829.0,91838.0
4,1005,AL,Barbour,7.0,-2.4,3.8,2.9,5.1,6.0,8.4,...,767.0,929.0,7930.0,8859.0,944.0,9096.0,665.0,9698.0,10363.0,8298.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3273,72145,PR,Vega Baja,NaN,NaN,9.6,1.0,10.4,12.4,13.9,...,1899.0,2288.0,11869.0,14157.0,2403.0,14601.0,2670.0,18445.0,21115.0,13414.0
3274,72147,PR,Vieques,NaN,NaN,7.0,6.9,16.5,14.5,10.6,...,362.0,442.0,2710.0,3152.0,491.0,3080.0,362.0,2955.0,3317.0,3027.0
3275,72149,PR,Villalba,NaN,NaN,15.8,2.2,15.8,19.4,20.2,...,1540.0,1724.0,6196.0,7920.0,1768.0,8184.0,1256.0,8223.0,9479.0,7557.0
3276,72151,PR,Yabucoa,NaN,NaN,13.1,2.0,14.3,16.5,16.9,...,1605.0,2096.0,7546.0,9642.0,2427.0,10169.0,2077.0,9348.0,11425.0,9000.0
3277,72153,PR,Yauco,NaN,NaN,14.6,1.1,14.7,17.2,18.8,...,2031.0,2366.0,8665.0,11031.0,2391.0,11350.0,2184.0,14451.0,16635.0,10160.0

In [31]:
df4

,FIPStxt,State,County,RuralUrbanContinuumCode2013,UrbanInfluenceCode2013,RuralUrbanContinuumCode2003,UrbanInfluenceCode2003,Metro2013,Nonmetro2013,Micropolitan2013,...,FarmDependent2003,ManufacturingDependent2000,LowEducation2000,RetirementDestination2000,PersistentPoverty2000,Noncore2013,Type_2015_Nonspecialized_NO,Metro_Adjacent2013,PersistentChildPoverty2004,RecreationDependent2000
0,1001,AL,Autauga,2.0,2.0,2.0,2.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,1003,AL,Baldwin,3.0,2.0,4.0,5.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
2,1005,AL,Barbour,6.0,6.0,6.0,6.0,0.0,1.0,0.0,...,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0
3,1007,AL,Bibb,1.0,1.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
4,1009,AL,Blount,1.0,1.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3220,72145,PR,Vega Baja,1.0,1.0,1.0,1.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN
3221,72147,PR,Vieques,7.0,12.0,7.0,12.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,0.0,NaN,NaN
3222,72149,PR,Villalba,2.0,2.0,2.0,2.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN
3223,72151,PR,Yabucoa,1.0,1.0,1.0,1.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN
3224,72153,PR,Yauco,2.0,2.0,3.0,2.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN

In [30]:
df5

,FIPS,State,County,Vets18OPct,GulfWar2VetsPct,GulfWar1VetsPct,VietnamEraVetsPct,KoreanWarVetsPct,WW2VetsPct,MaleVetsPct,...,PctVetsDisabilty,PctNonVetsDisabilty,CivPopVets18to64Num,CivPop18ONum,Vets18ONum,NonVetsDisabilty,NonVetsPoor,VetsDisabilty,VetsPoor,CLFVets18to64Num
0,0,US,United States,7.286424,19.312637,20.719749,35.710834,8.118271,3.504486,91.118977,...,18.294605,9.935824,9143042.0,250195726.0,18230322.0,18404982.0,23793332.0,1648352.0,734648.0,7003778.0
1,1000,AL,Alabama,8.766780,21.520743,24.649992,36.226670,7.214868,2.170154,89.794281,...,22.349785,13.814824,177164.0,3766571.0,330207.0,373473.0,441454.0,38993.0,16418.0,126372.0
2,1001,AL,Autauga,12.635111,37.708649,37.500000,31.885432,7.169954,4.191958,87.253414,...,20.056854,15.398961,3182.0,41725.0,5272.0,4624.0,4432.0,635.0,146.0,2754.0
3,1003,AL,Baldwin,11.815500,19.030667,22.331282,42.516401,7.877740,2.380105,92.147689,...,17.060425,11.288564,9337.0,166417.0,19663.0,12737.0,11811.0,1567.0,705.0,6996.0
4,1005,AL,Barbour,6.622120,15.737952,16.942771,48.493976,7.605422,3.388554,92.093373,...,26.706827,17.370544,605.0,20054.0,1328.0,2110.0,3408.0,133.0,77.0,301.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3273,72145,PR,Vega Baja,2.414881,11.287129,4.356436,35.049505,26.732673,2.574257,93.861386,...,54.907975,18.187919,326.0,41824.0,1010.0,5691.0,13335.0,179.0,93.0,150.0
3274,72147,PR,Vieques,5.571552,0.000000,0.000000,45.736434,16.795866,0.000000,100.000000,...,0.000000,3.400680,98.0,6946.0,387.0,170.0,1889.0,0.0,0.0,42.0
3275,72149,PR,Villalba,2.459344,23.665893,16.705336,15.081206,16.937355,0.000000,97.679814,...,45.669291,19.790817,254.0,17525.0,431.0,2668.0,5988.0,116.0,39.0,166.0
3276,72151,PR,Yabucoa,2.240824,5.123967,29.586777,32.561983,8.264463,0.000000,98.512397,...,20.168067,8.764562,357.0,26999.0,605.0,1753.0,9835.0,72.0,200.0,246.0
3277,72153,PR,Yauco,2.615428,2.000000,12.800000,39.200000,12.933333,0.933333,98.933333,...,47.712418,25.381248,306.0,28676.0,750.0,5276.0,9605.0,146.0,16.0,91.0

In [28]:
# df6.head()
df6

,FIPS,State,County,Median_HH_Inc_ACS,PerCapitaInc,Poverty_Rate_0_17_ACS,Poverty_Rate_ACS,Deep_Pov_All,Deep_Pov_Children,NumAll_inPOV_ACS,PCTPOV017,POV017,MedHHInc,POVALL,PCTPOVALL,Num_inPOV_0_17_ACS
0,0,US,United States,62843.0,34103.0,18.519621,13.422426,5.985652,8.155789,42510843.0,16.8,12000470.0,65712.0,39490096.0,12.3,13377778.0
1,1000,AL,Alabama,50536.0,27928.0,23.900209,16.742549,7.410636,11.152622,795989.0,21.9,233890.0,51771.0,747478.0,15.6,258068.0
2,1001,AL,Autauga,58731.0,29819.0,23.215238,15.185172,6.261607,9.592381,8340.0,15.9,2040.0,58233.0,6723.0,12.1,3047.0
3,1003,AL,Baldwin,58320.0,32626.0,13.364308,10.354073,4.046885,5.656490,21704.0,13.5,6323.0,59871.0,22360.0,10.1,6098.0
4,1005,AL,Barbour,32525.0,18473.0,50.142884,30.668689,15.042156,31.491713,6875.0,41.0,2050.0,35972.0,5909.0,27.1,2632.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3273,72145,PR,Vega Baja,19617.0,11116.0,53.553078,45.180155,24.684993,33.756665,23486.0,NaN,NaN,NaN,NaN,NaN,5524.0
3274,72147,PR,Vieques,14936.0,10426.0,83.101992,45.879344,26.351273,64.695232,3947.0,NaN,NaN,NaN,NaN,NaN,1377.0
3275,72149,PR,Villalba,19877.0,10894.0,62.662202,47.796793,27.341329,41.335287,10641.0,NaN,NaN,NaN,NaN,NaN,2994.0
3276,72151,PR,Yabucoa,16295.0,9929.0,66.210543,53.118460,27.148239,40.988960,17766.0,NaN,NaN,NaN,NaN,NaN,4258.0
3277,72153,PR,Yauco,14743.0,8404.0,60.110185,49.032020,27.915295,33.338297,17273.0,NaN,NaN,NaN,NaN,NaN,4037.0

In [81]:
df69 = df2.merge(df3,how='left')
df69 = df69.merge(df4, how='left')
df69 = df69.merge(df5, how='left')
df69 = df69.merge(df6, how='left')
# df69 = df69.merge(df1, how = 'left')
df69

,State,County,PopChangeRate1819,PopChangeRate1019,TotalPopEst2019,NetMigrationRate1019,NaturalChangeRate1019,Net_International_Migration_Rate_2010_2019,PopChangeRate0010,NetMigrationRate0010,...,Poverty_Rate_ACS,Deep_Pov_All,Deep_Pov_Children,NumAll_inPOV_ACS,PCTPOV017,POV017,MedHHInc,POVALL,PCTPOVALL,Num_inPOV_0_17_ACS
0,US,United States,0.475,6.116,328239523,2.485,3.631,2.485,9.709135,NaN,...,13.422426,5.985652,8.155789,42510843.0,16.8,12000470.0,65712.0,39490096.0,12.3,13377778.0
1,AL,Alabama,0.317,2.461,4903185,1.059,1.402,0.809,7.479841,3.304431,...,16.742549,7.410636,11.152622,795989.0,21.9,233890.0,51771.0,747478.0,15.6,258068.0
2,AL,Autauga,0.605,2.001,55869,0.686,1.315,-0.029,24.959355,11.867063,...,15.185172,6.261607,9.592381,8340.0,15.9,2040.0,58233.0,6723.0,12.1,3047.0
3,AL,Baldwin,2.469,21.911,223234,21.001,0.910,0.714,29.804508,26.166320,...,10.354073,4.046885,5.656490,21704.0,13.5,6323.0,59871.0,22360.0,10.1,6098.0
4,AL,Barbour,-0.748,-9.664,24686,-8.797,-0.867,0.161,-5.444590,-4.800965,...,30.668689,15.042156,31.491713,6875.0,41.0,2050.0,35972.0,5909.0,27.1,2632.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3322,PR,Vega Baja,NaN,-16.015,50023,NaN,NaN,NaN,-3.660644,NaN,...,45.180155,24.684993,33.756665,23486.0,NaN,NaN,NaN,NaN,NaN,5524.0
3323,PR,Vieques,NaN,-9.963,8386,NaN,NaN,NaN,2.141445,NaN,...,45.879344,26.351273,64.695232,3947.0,NaN,NaN,NaN,NaN,NaN,1377.0
3324,PR,Villalba,NaN,-17.803,21372,NaN,NaN,NaN,-6.591911,NaN,...,47.796793,27.341329,41.335287,10641.0,NaN,NaN,NaN,NaN,NaN,2994.0
3325,PR,Yabucoa,NaN,-14.765,32282,NaN,NaN,NaN,-3.325180,NaN,...,53.118460,27.148239,40.988960,17766.0,NaN,NaN,NaN,NaN,NaN,4258.0
3326,PR,Yauco,NaN,-19.731,33575,NaN,NaN,NaN,-9.358831,NaN,...,49.032020,27.915295,33.338297,17273.0,NaN,NaN,NaN,NaN,NaN,4037.0

In [89]:
df69.set_index('FIPS', inplace = True)
df69

,State,County,PopChangeRate1819,PopChangeRate1019,TotalPopEst2019,NetMigrationRate1019,NaturalChangeRate1019,Net_International_Migration_Rate_2010_2019,PopChangeRate0010,NetMigrationRate0010,...,Poverty_Rate_ACS,Deep_Pov_All,Deep_Pov_Children,NumAll_inPOV_ACS,PCTPOV017,POV017,MedHHInc,POVALL,PCTPOVALL,Num_inPOV_0_17_ACS
FIPS,,,,,,,,,,,,,,,,,,,,,
0,US,United States,0.475,6.116,328239523,2.485,3.631,2.485,9.709135,NaN,...,13.422426,5.985652,8.155789,42510843.0,16.8,12000470.0,65712.0,39490096.0,12.3,13377778.0
1000,AL,Alabama,0.317,2.461,4903185,1.059,1.402,0.809,7.479841,3.304431,...,16.742549,7.410636,11.152622,795989.0,21.9,233890.0,51771.0,747478.0,15.6,258068.0
1001,AL,Autauga,0.605,2.001,55869,0.686,1.315,-0.029,24.959355,11.867063,...,15.185172,6.261607,9.592381,8340.0,15.9,2040.0,58233.0,6723.0,12.1,3047.0
1003,AL,Baldwin,2.469,21.911,223234,21.001,0.910,0.714,29.804508,26.166320,...,10.354073,4.046885,5.656490,21704.0,13.5,6323.0,59871.0,22360.0,10.1,6098.0
1005,AL,Barbour,-0.748,-9.664,24686,-8.797,-0.867,0.161,-5.444590,-4.800965,...,30.668689,15.042156,31.491713,6875.0,41.0,2050.0,35972.0,5909.0,27.1,2632.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72145,PR,Vega Baja,NaN,-16.015,50023,NaN,NaN,NaN,-3.660644,NaN,...,45.180155,24.684993,33.756665,23486.0,NaN,NaN,NaN,NaN,NaN,5524.0
72147,PR,Vieques,NaN,-9.963,8386,NaN,NaN,NaN,2.141445,NaN,...,45.879344,26.351273,64.695232,3947.0,NaN,NaN,NaN,NaN,NaN,1377.0
72149,PR,Villalba,NaN,-17.803,21372,NaN,NaN,NaN,-6.591911,NaN,...,47.796793,27.341329,41.335287,10641.0,NaN,NaN,NaN,NaN,NaN,2994.0
72151,PR,Yabucoa,NaN,-14.765,32282,NaN,NaN,NaN,-3.325180,NaN,...,53.118460,27.148239,40.988960,17766.0,NaN,NaN,NaN,NaN,NaN,4258.0
72153,PR,Yauco,NaN,-19.731,33575,NaN,NaN,NaN,-9.358831,NaN,...,49.032020,27.915295,33.338297,17273.0,NaN,NaN,NaN,NaN,NaN,4037.0

In [92]:
df69 = df69.merge(df1, on = ['FIPS'])

In [93]:
df69

,State,County,PopChangeRate1819,PopChangeRate1019,TotalPopEst2019,NetMigrationRate1019,NaturalChangeRate1019,Net_International_Migration_Rate_2010_2019,PopChangeRate0010,NetMigrationRate0010,...,Price-RangeQ42020,Latitude (generated),Longitude (generated),ABS-diff price Q1 2021,ABS-diff price Q4 2020,abs-diff-price,Diff price Q3 2020,Diff price Q4 2020,Q1 2021,Q4 2020 Price
FIPS,,,,,,,,,,,,,,,,,,,,,
0,US,United States,0.475,6.116,328239523,2.485,3.631,2.485,9.709135,NaN,...,0,0.0000,0.0000,0.000,0.000,0.000,0.000,0.000000,0.0,0.0
1001,AL,Autauga,0.605,2.001,55869,0.686,1.315,-0.029,24.959355,11.867063,...,"$150,000-$350,000",32.5081,-86.6513,0.063,0.052,0.037,0.037,0.052215,163383.0,161743.0
1003,AL,Baldwin,2.469,21.911,223234,21.001,0.910,0.714,29.804508,26.166320,...,"$150,000-$350,000",30.7725,-87.7842,0.139,0.119,0.036,0.036,0.118684,238582.0,234357.0
1005,AL,Barbour,-0.748,-9.664,24686,-8.797,-0.867,0.161,-5.444590,-4.800965,...,"Less than $150,000",31.8832,-85.3931,0.034,0.051,0.036,0.036,-0.051247,96994.0,95277.0
1007,AL,Bibb,0.121,-2.081,22394,-2.099,0.017,0.525,10.030731,6.427962,...,"Less than $150,000",33.0388,-87.0967,0.023,0.033,0.047,0.047,-0.032950,99436.0,98445.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56037,WY,Sweetwater,-1.202,-2.825,42343,-9.292,6.467,0.140,16.465052,2.595068,...,"$150,000-$350,000",41.6405,-108.9887,0.006,0.011,0.025,0.025,-0.010652,217245.0,213576.0
56039,WY,Teton,0.838,10.180,23464,3.226,6.954,2.240,16.673059,4.390403,...,"$750,000-$1,000,000",43.9385,-110.5501,0.055,0.037,0.025,0.025,0.037229,915682.0,900218.0
56041,WY,Uinta,-0.325,-4.092,20226,-10.920,6.828,-0.346,6.969912,-2.400081,...,"$150,000-$350,000",41.3156,-110.5477,0.007,0.024,0.025,0.025,-0.023638,184911.0,181789.0
56043,WY,Washakie,-0.914,-8.499,7805,-8.910,0.410,-0.352,2.943660,-5.307804,...,"$150,000-$350,000",43.8356,-107.6602,0.027,0.009,0.025,0.025,0.009179,175190.0,172232.0
56045,WY,Weston,0.043,-3.765,6927,-4.321,0.556,1.695,8.488862,5.379508,...,"$150,000-$350,000",43.8403,-104.5684,0.014,0.031,0.025,0.025,-0.030673,175719.0,172751.0

In [104]:
blackpopchangerate = []
immigrationrate00_10 = []
hispanicpct2010 = []
popdensity2010 = []
asianpct2010 = []
blackpct2010 = []
nativepct2010 = []
white2010 = []
alphax = []
adjr = []

In [105]:
for i in ['UnempRate2020', 'PerCapitaInc', 'Poverty_Rate_ACS', 'MedHHInc', 'Q1 2021']:
    y = df69[i]
    X = sm.add_constant(df69[['NonHispanicBlackPopChangeRate0010',
                             'Immigration_Rate_2000_2010', 
                             'HispanicPct2010', 
                             'PopDensity2010',
                             'AsianNonHispanicPct2010',
                             'BlackNonHispanicPct2010',
                             'NativeAmericanNonHispanicPct2010',
                             'WhiteNonHispanicPct2010']])
    results = sm.OLS(y,X,missing='drop').fit()
    alpha = (results.params['const'])
    alphax.append(alpha)
    blackpopchangerate.append(results.params['NonHispanicBlackPopChangeRate0010'])
    immigrationrate00_10.append(results.params['Immigration_Rate_2000_2010'])
    hispanicpct2010.append(results.params['HispanicPct2010'])
    popdensity2010.append(results.params['PopDensity2010'])
    asianpct2010.append(results.params['AsianNonHispanicPct2010'])
    blackpct2010.append(results.params['BlackNonHispanicPct2010'])
    nativepct2010.append(results.params['NativeAmericanNonHispanicPct2010'])
    white2010.append(results.params['WhiteNonHispanicPct2010'])
    adjr.append(results.rsquared_adj)

In [106]:
ad = pd.DataFrame(df69['UnempRate2020'].describe())
bd = pd.DataFrame(df69['PerCapitaInc'].describe())
cd = pd.DataFrame(df69['Poverty_Rate_ACS'].describe())
dd = pd.DataFrame(df69['MedHHInc'].describe())
ed = pd.DataFrame(df69['Q1 2021'].describe())
test3 = pd.concat([ad, bd, cd, dd, ed], axis=1)
test3.columns = ['Unemployment Rate 2020', 
                 'Per Capita Income (2019 inflation adjusted)', 
                 'Poverty Rate (2015-19)', 
                 'Median Houshold Income (2019 inflation adjusted)',
                 'Property Values Q1 2021']
test3

,Unemployment Rate 2020,Per Capita Income (2019 inflation adjusted),Poverty Rate (2015-19),Median Houshold Income (2019 inflation adjusted),Property Values Q1 2021
count,3186.000000,3187.000000,3187.000000,3186.000000,3.165000e+03
mean,6.745009,28187.450580,15.102747,55882.942561,1.729315e+05
std,2.276780,6926.529867,6.317674,14720.262470,1.132172e+05
min,1.700000,10388.000000,2.428811,24732.000000,0.000000e+00
25%,5.200000,23649.000000,10.569728,46287.500000,1.051550e+05
50%,6.500000,27367.000000,14.218831,53366.500000,1.412840e+05
75%,8.000000,31320.500000,18.460614,62229.500000,1.995710e+05
max,22.500000,76592.000000,55.451837,151806.000000,1.185951e+06

In [108]:
finale = pd.DataFrame({'Dependent Variable':['Unemployment Rate 2020', 
                                             'Per Capita Income', 
                                             'Poverty Rate', 
                                             'Median Household Income', 
                                             'Property Values Q12021'],
                       'Alpha':alphax,
                       'Black Population Change Rate (2000-2010)':blackpopchangerate,
                       'Immigration Rate (2000-2010)':immigrationrate00_10,
                       'Percentage Hispanic 2010':hispanicpct2010,
                       'Percentage Asian 2010':asianpct2010,
                       'Percentage Black 2010': blackpct2010,
                       'Percentage Native American': nativepct2010,
                       'Percentage White 2010': white2010,
                       'Population Density 2010': popdensity2010,
                       'Adjusted R Squared': adjr})
finale.set_index('Dependent Variable', inplace = True)
finale

,Alpha,Black Population Change Rate (2000-2010),Immigration Rate (2000-2010),Percentage Hispanic 2010,Percentage Asian 2010,Percentage Black 2010,Percentage Native American,Percentage White 2010,Population Density 2010,Adjusted R Squared
Dependent Variable,,,,,,,,,,
Unemployment Rate 2020,23.941783,0.000085,-0.136918,-0.143709,-0.137372,-0.141100,-0.151223,-0.181069,0.000110,0.129747
Per Capita Income,-3823.514081,-0.497190,659.079630,192.579001,1348.410507,193.838397,205.544466,328.877883,0.582324,0.341198
Poverty Rate,11.411463,0.000174,-0.142525,0.111194,-0.379114,0.222405,0.272819,0.012126,-0.000060,0.336340
Median Household Income,-25040.492016,-0.584558,1331.557663,656.475197,3348.168565,523.227500,647.513292,818.772106,0.336552,0.331578
Property Values Q12021,576938.056263,-3.485747,14764.582275,-5102.100002,13063.211278,-5452.313007,-5535.314050,-4350.444671,12.366411,0.454324